spring.application.name=capstone-backend

# 1. Database (Supabase) 설정
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA/Hibernate 설정 (엔티티 기반 DB 테이블 자동 검증)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# 3. Redis (Upstash) 설정
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

# 4. AI 에이전트 서버 주소 (FastAPI)
ai.agent.url=${AI_AGENT_URL}

# 5. Flyway 활성화
spring.flyway.enabled=true

# API 문서 자동 생성 활성화(swagger)
springdoc.api-docs.enabled=true

# HikariCP 커넥션 풀 개수를 .env의 값과 동기화
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE}
# 무료 티어 Supabase 최대 커넥션 풀 개수가 15개임. 4명이서 개발을 할 경우에 4 * DB_POOL_SIZE 만큼 DB에 점유함.
# 무료 티어 4 * DB_POOL_SIZE < 15하려면, DB_POOL_SIZE를 3으로 해야할지도 (docker로 postgresql 띄우면 최대 커넥션 풀 개수가 100임)
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.pool-name=HikariPool-JPA-Isolated
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# Clerk 설정
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URL}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER}
